spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-student-id
          uri: lb://service-student
          predicates:
            Path=/api/service-student/**
      metrics:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

logging:
  level.org.springframework.cloud.gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9090