eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#secret key - should be encrypted
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
#2 minutes validity
  expiration: 172800
#ignore null fields in json
spring:
  application:
    name: auth-server
  jackson:
    default-property-inclusion: NON_NULL

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true