#ignore null fields in json
spring:
  application:
    name: auth-server
  jackson:
    default-property-inclusion: NON_NULL
server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

#secret key - should be encrypted
jwt:
  secret: ${JWT_KEY}
  expiration: 86400

