spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres
      mode: always
  kafka:
    consumer:
      group-id: service_retention
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  error:
    include-stacktrace: on_param
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: service-retention
    description: Retention Service Application
    version: 0.0.1
    author: Lannys Nguyen
