server:
  error:
    include-stacktrace: on-param
  port: 8082
spring:
  kafka:
    consumer:
      group-id: service_mail_consumer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: service-mail-sender
    description: Mail Sender Application
    version: 0.0.1
    author: Lannys Nguyen