spring:
  profiles:
    active: native
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations:
            ${CONFIG_SERVER_PROPERTIES_APPLICATION_PATH},
            ${CONFIG_SERVER_PROPERTIES_GLOBAL_PATH}

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nphoangtu/student-academic-affairs-management/
          search-paths:
            - "service-config-properties/{application}/{profile}"
            - "service-config-properties/global/{profile}"



