management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thesis
    username: postgres
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      platform: postgres
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  basic:
    enabled: false

server:
  error:
    include-stacktrace: on-param
  port: 8081