spring:
  application:
    name: service-retetion
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
      encoding: UTF-8
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      mode: always
server:
  error:
    include-stacktrace: on_param
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka