spring:
  cloud:
    gateway:
      loadbalancer:
        use404: true
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
server:
  error:
    include-stacktrace: on_param
  port: 9093
#secret key - should be encrypted
jwt:
  secret: ${JWT_KEY}
  expiration: 86400

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

