spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      metrics:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: *

logging:
  level.org.springframework.cloud.gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
