spring:
  cloud:
    gateway:
      metrics:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
server:
  error:
    include-stacktrace: on_param
  port: 9093
#secret key - should be encrypted
jwt:
  secret: ${JWT_KEY}
  #2 minutes validity
  expiration: 172800

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

