spring:
  cloud:
    gateway:
      metrics:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false

#secret key - should be encrypted
jwt:
  secret: ${JWT_KEY}
  #2 minutes validity
  expiration: 172800

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: *

logging:
  level.org.springframework.cloud.gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9092