spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      studentCreated: STUDENT_CREATED_TOPIC
      retentionRequested: RETENTION_REQUESTED_TOPIC
      retentionSucceeded: RETENTION_SUCCEEDED_TOPIC